name = "aiken-lang/hello_world"
version = "0.0.0"
license = "Apache-2.0"
description = "Aiken contracts for project 'aiken-lang/hello_world'"

[repository]
user = "aiken-lang"
project = "hello_world"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "main"
source = "github"
